<a href="https://colab.research.google.com/github/24f1000525/ML/blob/main/Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [38]:
import pandas as pd
import numpy as np

In [39]:
from sklearn.datasets import load_iris
data=load_iris()
X,y=data.data,data.target
print(X.shape,y.shape)

(150, 4) (150,)


In [40]:
type(data)

sklearn.utils._bunch.Bunch

In [41]:
type(X)

numpy.ndarray

In [42]:
X,y=load_iris(as_frame=True,return_X_y=True)

In [43]:
type(X)

pandas.core.frame.DataFrame

In [44]:
X.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
0,5.1,3.5,1.4,0.2
1,4.9,3.0,1.4,0.2
2,4.7,3.2,1.3,0.2
3,4.6,3.1,1.5,0.2
4,5.0,3.6,1.4,0.2


In [45]:
from sklearn.datasets import fetch_california_housing
X,y=fetch_california_housing(as_frame=True,return_X_y=True)


In [46]:
X.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25


In [47]:
from sklearn.datasets import make_regression
X,y=make_regression(n_samples=100,n_features=5,random_state=42)

In [48]:
X[:5,:]

array([[-0.93782504,  0.51504769,  0.51503527,  3.85273149,  0.51378595],
       [ 1.0889506 , -0.71530371,  0.06428002,  0.67959775, -1.07774478],
       [-0.60170661, -1.05771093,  1.85227818,  0.82254491, -0.01349722],
       [ 0.8219025 ,  0.09176078,  0.08704707, -1.98756891, -0.29900735],
       [ 1.54993441,  0.81351722, -0.78325329, -1.23086432, -0.32206152]])

In [49]:
from sklearn.feature_extraction import DictVectorizer
v = DictVectorizer(sparse=False)
D = [{'foo': 1, 'bar': 2}, {'foo': 3, 'baz': 1}]
X = v.fit_transform(D)

In [50]:
X

array([[2., 0., 1.],
       [0., 1., 3.]])

### Handling Missing Value


SimpleImputer

In [51]:
X=np.array([[1,2],[np.nan,3],[2,5],[3,3]])

In [52]:
from sklearn.impute import SimpleImputer

imputer=SimpleImputer(strategy='mean')
imputer.fit_transform(X)

array([[1., 2.],
       [2., 3.],
       [2., 5.],
       [3., 3.]])

In [53]:
x_test=np.array([[1,2],[np.nan,9]])
X_test_imputed=imputer.transform(x_test)
X_test_imputed

array([[1., 2.],
       [2., 9.]])

KNNImputer

In [54]:
from sklearn.impute import KNNImputer
imputer=KNNImputer(n_neighbors=2)
x_imputed=imputer.fit_transform(X)
x_imputed

array([[1., 2.],
       [2., 3.],
       [2., 5.],
       [3., 3.]])

### Scaling

In [55]:
from sklearn.preprocessing import StandardScaler
x_scaled=StandardScaler().fit_transform(X)

In [56]:
x_scaled

array([[-1.22474487, -1.14707867],
       [        nan, -0.22941573],
       [ 0.        ,  1.60591014],
       [ 1.22474487, -0.22941573]])

In [66]:
x_test=np.array([[1,2],[3,8]])

In [67]:
from sklearn.preprocessing import FunctionTransformer
transformer=FunctionTransformer(np.log2,validate=True)
x_transformed=transformer.fit_transform(x_test)

In [68]:
x_transformed

array([[0.       , 1.       ],
       [1.5849625, 3.       ]])

In [73]:
from sklearn.preprocessing import PolynomialFeatures
poly=PolynomialFeatures(degree=2)
x_poly=poly.fit_transform(x_test)

In [74]:
x_poly

array([[ 1.,  1.,  2.,  1.,  2.,  4.],
       [ 1.,  3.,  8.,  9., 24., 64.]])

In [75]:
np.random.seed(42)
data=pd.DataFrame({
    'age':np.random.randint(18,60,30),
    'salary':np.random.randint(20000,100000,30),
    'experience':np.random.choice([1,2,3,4,np.nan],30),
    'education':np.random.choice(['bachelor','master','phd'],30),
    'department':np.random.choice(['hr','sales','marketing'],30),
    'city':np.random.choice(['newyork','london','paris'],30)
})
y=np.random.choice([0,1],30)

In [76]:
data.head()

,age,salary,experience,education,department,city
0,56,79150,NaN,phd,marketing,london
1,46,85725,2.0,phd,marketing,newyork
2,32,55773,2.0,bachelor,sales,london
3,25,87435,4.0,phd,marketing,newyork
4,38,76886,2.0,bachelor,marketing,newyork


In [86]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder,OrdinalEncoder,StandardScaler
from sklearn.impute import SimpleImputer

preprocessor=ColumnTransformer(
    transformers=[
        ('imp',SimpleImputer(strategy='mean'),['experience']),
        ('ss',StandardScaler(),['age','salary']),
        ('oe',OneHotEncoder(sparse_output=False),['department','city']),
        ('ohe',OrdinalEncoder(categories=[['bachelor','master','phd']]),['education'])
    ],
    remainder='passthrough'
)
preprocessor.set_output(transform='pandas')

x_transformed=preprocessor.fit_transform(data)

x_transformed.head(10)



,imp__experience,ss__age,ss__salary,oe__department_hr,oe__department_marketing,oe__department_sales,oe__city_london,oe__city_newyork,oe__city_paris,ohe__education
0,2.347826,1.425355,0.516585,0.0,1.0,0.0,1.0,0.0,0.0,2.0
1,2.000000,0.541871,0.797614,0.0,1.0,0.0,0.0,1.0,0.0,2.0
2,2.000000,-0.695008,-0.482594,0.0,0.0,1.0,1.0,0.0,0.0,0.0
3,4.000000,-1.313447,0.870703,0.0,1.0,0.0,0.0,1.0,0.0,2.0
4,2.000000,-0.164917,0.419817,0.0,1.0,0.0,0.0,1.0,0.0,0.0
5,2.000000,1.425355,0.843690,1.0,0.0,0.0,1.0,0.0,0.0,1.0
6,4.000000,-0.341614,-0.663051,0.0,1.0,0.0,1.0,0.0,0.0,2.0
7,4.000000,0.011780,-1.524601,0.0,1.0,0.0,1.0,0.0,0.0,1.0
8,1.000000,-1.048402,0.941526,0.0,0.0,1.0,0.0,0.0,1.0,0.0
9,2.347826,-1.048402,-1.845337,0.0,0.0,1.0,1.0,0.0,0.0,2.0


In [87]:
preprocessor.named_transformers_['ss'].mean_

array([3.98666667e+01, 6.70638667e+04])

In [88]:
preprocessor.get_feature_names_out()

array(['imp__experience', 'ss__age', 'ss__salary', 'oe__department_hr',
       'oe__department_marketing', 'oe__department_sales',
       'oe__city_london', 'oe__city_newyork', 'oe__city_paris',
       'ohe__education'], dtype=object)