In [1]:
import numpy as np

vectors representation in numpy

In [7]:
x=np.array([2,5,3,7])
y=np.array([4,6,7,5])

vector addition

In [6]:
z=x+y
z

array([ 6, 11, 10, 12])

element wise multiplication

In [9]:
z=x*y
z

array([ 8, 30, 21, 35])

scaling vectors

In [10]:
z=3*x
z

array([ 6, 15,  9, 21])

element wise function of vectors

In [11]:
z=x**2
z

array([ 4, 25,  9, 49])

In [15]:
z=np.log(x)
z

array([0.69314718, 1.60943791, 1.09861229, 1.94591015])

dot product

In [16]:
z=np.dot(x,y)
z

np.int64(94)

shape of vector

In [21]:
x.shape
x.shape[0]==len(x)

True

vectors with all zero

In [22]:
s=np.array([0 for _ in range(4)])
s

array([0, 0, 0, 0])

In [29]:
s=np.ones(6)
s

array([1., 1., 1., 1., 1., 1.])

In [30]:
s=np.zeros(5)
s

array([0., 0., 0., 0., 0.])